name: CI on Pull Request

on:
  pull_request:

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      workflows: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Format code
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: auto format code'
          branch: ${{ github.head_ref }}

      - name: Lint
        run: npm run lint
